# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/ca.yaml, data/north_america_informal.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/ca'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module CA # :nodoc:
    def self.defined_regions
      [:ca, :ca_qc, :ca_ab, :ca_on, :ca_sk, :ca_mb, :ca_bc, :ca_nf, :ca_nt, :ca_nu, :ca_ns, :ca_yk, :us]
    end

    def self.holidays_by_month
      {
              0 => [{:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :key => "", :name => "Good Friday", :regions => [:ca]},
            {:function => lambda { |year| Holidays.easter(year) }, :function_id => "easter(year)", :key => "", :name => "Easter Sunday", :regions => [:ca]},
            {:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :type => :informal, :key => "", :name => "Easter Monday", :regions => [:ca]}],
      1 => [{:mday => 1, :key => "", :name => "New Year's Day", :regions => [:ca]},
            {:mday => 2, :key => "", :name => "New Year's", :regions => [:ca_qc]}],
      2 => [{:wday => 1, :week => 3, :key => "", :name => "Family Day", :regions => [:ca_ab, :ca_on, :ca_sk]},
            {:wday => 1, :week => 3, :key => "", :name => "Louis Riel Day", :regions => [:ca_mb]},
            {:wday => 1, :week => 2, :key => "", :name => "BC Family Day", :regions => [:ca_bc]},
            {:mday => 2, :type => :informal, :key => "", :name => "Groundhog Day", :regions => [:us, :ca]},
            {:mday => 14, :type => :informal, :key => "", :name => "Valentine's Day", :regions => [:us, :ca]}],
      3 => [{:mday => 23, :key => "", :name => "St. George's Day", :regions => [:ca_nf]},
            {:mday => 17, :type => :informal, :key => "", :name => "St. Patrick's Day", :regions => [:us, :ca]}],
      5 => [{:function => lambda { |year| Holidays.ca_victoria_day(year) }, :function_id => "ca_victoria_day(year)", :key => "", :name => "Victoria Day", :regions => [:ca]},
            {:function => lambda { |year| Holidays.ca_victoria_day(year) }, :function_id => "ca_victoria_day(year)", :key => "", :name => "National Patriotes Day", :regions => [:ca_qc]},
            {:wday => 0, :week => 2, :type => :informal, :key => "", :name => "Mother's Day", :regions => [:us, :ca]},
            {:wday => 6, :week => 3, :type => :informal, :key => "", :name => "Armed Forces Day", :regions => [:us]}],
      6 => [{:mday => 24, :key => "", :name => "Discovery Day", :regions => [:ca_nf]},
            {:mday => 24, :key => "", :name => "Fête Nationale", :regions => [:ca_qc]},
            {:mday => 21, :key => "", :name => "National Aboriginal Day", :regions => [:ca_nt]},
            {:wday => 0, :week => 3, :type => :informal, :key => "", :name => "Father's Day", :regions => [:us, :ca]}],
      7 => [{:mday => 1, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Canada Day", :regions => [:ca]},
            {:mday => 12, :key => "", :name => "Orangemen's Day", :regions => [:ca_nf]},
            {:mday => 9, :key => "", :name => "Nunavut Day", :regions => [:ca_nu]}],
      8 => [{:wday => 1, :week => 1, :key => "", :name => "BC Day", :regions => [:ca_bc]},
            {:wday => 1, :week => 1, :key => "", :name => "Saskatchewan Day", :regions => [:ca_sk]},
            {:wday => 1, :week => 1, :key => "", :name => "Heritage Day", :regions => [:ca_ab]},
            {:wday => 1, :week => 1, :key => "", :name => "Natal Day", :regions => [:ca_ns]},
            {:wday => 1, :week => 1, :key => "", :name => "Civic Holiday", :regions => [:ca_on]},
            {:wday => 1, :week => 3, :key => "", :name => "Discovery Day", :regions => [:ca_yk]}],
      9 => [{:wday => 1, :week => 1, :key => "", :name => "Labour Day", :regions => [:ca]}],
      10 => [{:wday => 1, :week => 2, :key => "", :name => "Thanksgiving", :regions => [:ca]},
            {:mday => 31, :type => :informal, :key => "", :name => "Halloween", :regions => [:us, :ca]}],
      11 => [{:mday => 11, :key => "", :name => "Remembrance Day", :regions => [:ca]}],
      12 => [{:mday => 25, :key => "", :name => "Christmas Day", :regions => [:ca]},
            {:mday => 26, :key => "", :name => "Boxing Day", :regions => [:ca]}],
      4 => [{:mday => 1, :type => :informal, :key => "", :name => "April Fool's Day", :regions => [:us, :ca]},
            {:mday => 22, :type => :informal, :key => "", :name => "Earth Day", :regions => [:us, :ca]}]
      }
    end
  end

# Monday on or before May 24
def self.ca_victoria_day(year)
  date = Date.civil(year,5,24)
  if date.wday > 1
    date -= (date.wday - 1)
  elsif date.wday == 0
    date -= 6
  end
  date
end



end

Holidays.merge_defs(Holidays::CA.defined_regions, Holidays::CA.holidays_by_month)
