# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/ma.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/ma'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module MA # :nodoc:
    def self.defined_regions
      [:ma]
    end

    def self.holidays_by_month
      {
              1 => [{:mday => 1, :key => "", :name => "Ras l' âm", :regions => [:ma]},
            {:mday => 11, :key => "", :name => "Takdim watikat al-istiqlal", :regions => [:ma]}],
      5 => [{:mday => 1, :key => "", :name => "Eid Ash-Shughl", :regions => [:ma]}],
      7 => [{:mday => 30, :key => "", :name => "Eid Al-Ârch", :regions => [:ma]}],
      8 => [{:mday => 14, :key => "", :name => "Zikra Oued Ed-Dahab", :regions => [:ma]},
            {:mday => 20, :key => "", :name => "Thawrat al malik wa shâab", :regions => [:ma]},
            {:mday => 21, :key => "", :name => "Eid Al Milad", :regions => [:ma]}],
      11 => [{:mday => 6, :key => "", :name => "Eid Al Massira Al Khadra", :regions => [:ma]},
            {:mday => 18, :key => "", :name => "Eid Al Istiqulal", :regions => [:ma]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::MA.defined_regions, Holidays::MA.holidays_by_month)
