# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/pl.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/pl'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module PL # :nodoc:
    def self.defined_regions
      [:pl]
    end

    def self.holidays_by_month
      {
              0 => [{:function => lambda { |year| Holidays.easter(year)-52 }, :function_id => "easter(year)-52", :type => :informal, :key => "", :name => "Tłusty Czwartek", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)-47 }, :function_id => "easter(year)-47", :type => :informal, :key => "", :name => "Ostatki", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)-46 }, :function_id => "easter(year)-46", :type => :informal, :key => "", :name => "Środa Popielcowa", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)-7 }, :function_id => "easter(year)-7", :type => :informal, :key => "", :name => "Niedziela Palmowa", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)-3 }, :function_id => "easter(year)-3", :type => :informal, :key => "", :name => "Wielki Czwartek", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :type => :informal, :key => "", :name => "Wielki Piątek", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)-1 }, :function_id => "easter(year)-1", :type => :informal, :key => "", :name => "Wielka Sobota", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year) }, :function_id => "easter(year)", :key => "", :name => "Niedziela Wielkanocna", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :key => "", :name => "Poniedziałek Wielkanocny (Lany Poniedziałek)", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)+49 }, :function_id => "easter(year)+49", :key => "", :name => "Zesłanie Ducha Świętego (Zielone Świątki)", :regions => [:pl]},
            {:function => lambda { |year| Holidays.easter(year)+60 }, :function_id => "easter(year)+60", :key => "", :name => "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)", :regions => [:pl]}],
      1 => [{:mday => 1, :key => "", :name => "Nowy Rok", :regions => [:pl]},
            {:function => lambda { |year| Holidays.pl_trzech_kroli(year) }, :function_id => "pl_trzech_kroli(year)", :key => "", :name => "Objawienie Pańskie (święto Trzech Króli)", :regions => [:pl]},
            {:function => lambda { |year| Holidays.pl_trzech_kroli_informal(year) }, :function_id => "pl_trzech_kroli_informal(year)", :type => :informal, :key => "", :name => "Objawienie Pańskie (święto Trzech Króli)", :regions => [:pl]},
            {:mday => 21, :type => :informal, :key => "", :name => "Dzień Babci", :regions => [:pl]},
            {:mday => 22, :type => :informal, :key => "", :name => "Dzień Dziadka", :regions => [:pl]}],
      2 => [{:mday => 2, :type => :informal, :key => "", :name => "Ofiarowanie Pańskie (Matki Boskiej Gromnicznej)", :regions => [:pl]},
            {:mday => 14, :type => :informal, :key => "", :name => "Dzień Zakochanych (Walentynki)", :regions => [:pl]}],
      3 => [{:mday => 8, :type => :informal, :key => "", :name => "Dzień Kobiet", :regions => [:pl]},
            {:mday => 10, :type => :informal, :key => "", :name => "Dzień Mężczyzn", :regions => [:pl]}],
      4 => [{:mday => 1, :type => :informal, :key => "", :name => "Prima Aprilis", :regions => [:pl]},
            {:mday => 22, :type => :informal, :key => "", :name => "Międzynarodowy Dzień Ziemi", :regions => [:pl]}],
      5 => [{:mday => 1, :key => "", :name => "Święto Państwowe (Święto Pracy)", :regions => [:pl]},
            {:mday => 2, :type => :informal, :key => "", :name => "Dzień Flagi Rzeczpospolitej Polskiej", :regions => [:pl]},
            {:mday => 3, :key => "", :name => "Święto Narodowe Trzeciego Maja", :regions => [:pl]}],
      6 => [{:mday => 23, :type => :informal, :key => "", :name => "Dzień Ojca", :regions => [:pl]}],
      8 => [{:mday => 15, :key => "", :name => "Wniebowzięcie Najświętszej Maryi Panny", :regions => [:pl]},
            {:mday => 15, :key => "", :name => "Święto Wojska Polskiego", :regions => [:pl]}],
      9 => [{:mday => 30, :type => :informal, :key => "", :name => "Dzień Chłopaka", :regions => [:pl]}],
      10 => [{:mday => 14, :type => :informal, :key => "", :name => "Dzień Nauczyciela (Dzień Edukacji Narodowej)", :regions => [:pl]}],
      11 => [{:mday => 1, :key => "", :name => "Wszystkich Świętych", :regions => [:pl]},
            {:mday => 2, :type => :informal, :key => "", :name => "Dzień Zaduszny", :regions => [:pl]},
            {:mday => 11, :key => "", :name => "Narodowe Święto Niepodległości", :regions => [:pl]},
            {:mday => 29, :type => :informal, :key => "", :name => "Andrzejki", :regions => [:pl]}],
      12 => [{:mday => 4, :type => :informal, :key => "", :name => "Barbórka (Dzień Górnika, Naftowca i Gazownika)", :regions => [:pl]},
            {:mday => 6, :type => :informal, :key => "", :name => "Mikołajki", :regions => [:pl]},
            {:mday => 24, :type => :informal, :key => "", :name => "Wigilia Bożego Narodzenia", :regions => [:pl]},
            {:mday => 25, :key => "", :name => "pierwszy dzień Bożego Narodzenia", :regions => [:pl]},
            {:mday => 26, :key => "", :name => "drugi dzień Bożego Narodzenia", :regions => [:pl]},
            {:mday => 31, :type => :informal, :key => "", :name => "Sylwester", :regions => [:pl]}]
      }
    end
  end

# Poland: January 6 is holiday since 2011
def self.pl_trzech_kroli(year)
  year >= 2011 ? 6 : nil
end


# Poland: January 6 wasn't holiday before 2011
def self.pl_trzech_kroli_informal(year)
  year < 2011 ? 6 : nil
end



end

Holidays.merge_defs(Holidays::PL.defined_regions, Holidays::PL.holidays_by_month)
