# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/ro.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/ro'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module RO # :nodoc:
    def self.defined_regions
      [:ro]
    end

    def self.holidays_by_month
      {
              0 => [{:function => lambda { |year| Holidays.orthodox_easter(year) }, :function_id => "orthodox_easter(year)", :key => "", :name => "Paștele", :regions => [:ro]},
            {:function => lambda { |year| Holidays.orthodox_easter(year)+1 }, :function_id => "orthodox_easter(year)+1", :key => "", :name => "Paștele", :regions => [:ro]},
            {:function => lambda { |year| Holidays.orthodox_easter(year) + 49 }, :function_id => "orthodox_easter(year) + 49", :key => "", :name => "Rusaliile", :regions => [:ro]},
            {:function => lambda { |year| Holidays.orthodox_easter(year) + 50 }, :function_id => "orthodox_easter(year) + 50", :key => "", :name => "Rusaliile", :regions => [:ro]}],
      1 => [{:mday => 1, :key => "", :name => "Anul nou", :regions => [:ro]},
            {:mday => 2, :key => "", :name => "Anul nou", :regions => [:ro]}],
      5 => [{:mday => 1, :key => "", :name => "Ziua muncii", :regions => [:ro]}],
      8 => [{:mday => 15, :key => "", :name => "Adormirea Maicii Domnului", :regions => [:ro]}],
      11 => [{:mday => 30, :key => "", :name => "Sfântul Apostol Andrei", :regions => [:ro]}],
      12 => [{:mday => 1, :key => "", :name => "Ziua Națională", :regions => [:ro]},
            {:mday => 25, :key => "", :name => "Sărbătoarea Nașterii Domnului", :regions => [:ro]},
            {:mday => 26, :key => "", :name => "Sărbătoarea Nașterii Domnului", :regions => [:ro]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::RO.defined_regions, Holidays::RO.holidays_by_month)
