# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/sk.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/sk'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module SK # :nodoc:
    def self.defined_regions
      [:sk]
    end

    def self.holidays_by_month
      {
              0 => [{:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :key => "", :name => "Veľkonočný pondelok", :regions => [:sk]},
            {:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :key => "", :name => "Veľký piatok", :regions => [:sk]}],
      1 => [{:mday => 1, :key => "", :name => "Nový rok", :regions => [:sk]}],
      5 => [{:mday => 1, :key => "", :name => "Sviatok práce", :regions => [:sk]},
            {:mday => 8, :key => "", :name => "Deň víťazstva", :regions => [:sk]}],
      7 => [{:mday => 5, :key => "", :name => "Sviatok svätého Cyrila a svätého Metoda", :regions => [:sk]}],
      8 => [{:mday => 29, :key => "", :name => "Výročie Slovenského národného povstania", :regions => [:sk]}],
      9 => [{:mday => 1, :key => "", :name => "Deň Ústavy Slovenskej republiky", :regions => [:sk]},
            {:mday => 15, :key => "", :name => "Sedembolestná Panna Mária", :regions => [:sk]}],
      11 => [{:mday => 1, :key => "", :name => "Sviatok všetkých svätých", :regions => [:sk]},
            {:mday => 17, :key => "", :name => "Deň boja za slobodu a demokraciu", :regions => [:sk]}],
      12 => [{:mday => 24, :key => "", :name => "Štedrý deň", :regions => [:sk]},
            {:mday => 25, :key => "", :name => "1. sviatok vianočný", :regions => [:sk]},
            {:mday => 26, :key => "", :name => "2. sviatek vianočný", :regions => [:sk]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::SK.defined_regions, Holidays::SK.holidays_by_month)
