# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/za.yaml
  #
  # To use the definitions in this file, load it right after you load the
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/za'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module ZA # :nodoc:
    def self.defined_regions
      [:za]
    end

    def self.holidays_by_month
      {
              0 => [{:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :key => "", :name => "Good Friday", :regions => [:za]},
            {:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :key => "", :name => "Family Day", :regions => [:za]}],
      1 => [{:mday => 1, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "New Year's Day", :regions => [:za]}],
      3 => [{:mday => 21, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Human Rights Day", :regions => [:za]}],
      4 => [{:mday => 27, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Freedom Day", :regions => [:za]}],
      5 => [{:mday => 1, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Workers Day", :regions => [:za]}],
      6 => [{:mday => 16, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Youth Day", :regions => [:za]}],
      8 => [{:mday => 9, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "National Women's Day", :regions => [:za]}],
      9 => [{:mday => 24, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Heritage Day", :regions => [:za]}],
      12 => [{:mday => 16, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Day of Reconciliation", :regions => [:za]},
            {:mday => 25, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :key => "", :name => "Christmas Day", :regions => [:za]},
            {:mday => 26, :observed => lambda { |date| Holidays.to_weekday_if_boxing_weekend(date) }, :observed_id => "to_weekday_if_boxing_weekend", :key => "", :name => "Day of Goodwill", :regions => [:za]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::ZA.defined_regions, Holidays::ZA.holidays_by_month)
